### ISSUE TITLE
Won't build rpm's with BuildArch other than "noarch"

### ISSUE THREAD

**Issue by kwilliamszaf** [iovation/git-build-rpm#3]
Hi

I am trying to build an rpm in which the architecture is specified to be something other than "noarch".

Git-build-rpm fails because the version queried from the spec file is returned twice (e.g. "3.43.4" and not "3.4") by the rpmspec query command, and then there is a mismatch between the archive file that git-archive-all creates, and the one rpmbuild expects when git-build-rpm is run.

To reproduce it, simply change the BuildArch in git-build-rpm.spec to "x86_64" for example.

It seems like the parsing of the result from the rpmspec query is not correct, but I don't know perl at all to try and find out why.

Kind regards

**Comment by theory** [comment]
Hey @kwilliamszaf, would you confirm that 9b014b3 fixes the issue for you? I was able to replicate it and it seemed to fix it. Thanks!

**Comment by kwilliamszaf** [comment]
Yes. Great! Thanks!
