### ISSUE TITLE
Copy over SRPMs as well

### ISSUE THREAD

**Issue by remyabel** [iovation/git-build-rpm#7]
When interfacing with build systems like COPR the SRPM is also needed. I think the function here:

https://github.com/iovation/git-build-rpm/blob/adc9c51bb97ff4d6ca03290f9d547786afcf7f3c/bin/git-build-rpm#L131

could be extended to copy files from the SRPMs folder.

**Comment by theory** [comment]
Hi. You're right about SRPMs; I never use them, but I'm sure they're useful. Is there a reason you closed this issue, @remyabel?
