### ISSUE TITLE
How rpmbuild can pick python3 instead of python2

### ISSUE THREAD

**Issue by alpana17** [iovation/git-build-rpm#8]
I am using rpmbuild on Amazon Linux 2 ARM. It is picking python 2 by default.
How can I make it use python3

**Comment by sampowers** [comment]
rpmbuild is a dependency of, but not part of, git-build-rpm.  Which paths (/usr/bin/python, which could be a symbolic link to either python2 or python3 depending on system defailts) rpmbuild uses may depend on information in your project's rpm spec file, which is unfortunately outside the scope of what git-build-rpm can help you with.
